-- 코드를 입력하세요
SELECT
    DISTINCT(A.CART_ID)
FROM CART_PRODUCTS A
JOIN (
    SELECT CART_ID FROM CART_PRODUCTS
    WHERE NAME = 'Yogurt'
) B ON A.CART_ID = B.CART_ID
WHERE A.NAME = 'Milk'
ORDER BY A.CART_ID;
