# 1. 자동차 종류가 '트럭'인 자동차를 뽑아라
# 2. 트럭 중 대여 기록 별(GROUP BY)로 묶어라
# 3. 대여 금액(FEE)를 구하라
#    - 대여기간 7일 이상 : DAILY_FEE - (DAILY_FEE * 0.05)
#    - 대여기간 30일 이상 : DAILY_FEE - (DAILY_FEE * 0.08)
#    - 대여기간 90일 이상 : DAILY_FEE - (DAILY_FEE * 0.15)
# 4. 대여 금액 기준 내림차순, 대여 기록 ID 기준 내림차순


# CAR_RENTAL_COMPANY_CAR / CAR_RENTAL_COMPANY_RENTAL_HISTORY 
# CAR_RENTAL_COMPANY_DISCOUNT_PLAN
# SELECT HISTORY_ID,
# CASE
# WHEN DURATION_TYPE='7일 이상' THEN ROUND((DAILY_FEE-(DAILY_FEE*0.05))*(DATEDIFF(END_DATE, START_DATE)+1))
# WHEN DURATION_TYPE='30일 이상' THEN ROUND((DAILY_FEE-(DAILY_FEE*0.08))*(DATEDIFF(END_DATE, START_DATE)+1))
# WHEN DURATION_TYPE='90일 이상' THEN ROUND((DAILY_FEE-(DAILY_FEE*0.15))*(DATEDIFF(END_DATE, START_DATE)+1))
# END
# AS FEE
# FROM(
# SELECT HISTORY_ID, START_DATE, END_DATE, DAILY_FEE, DURATION_TYPE, DISCOUNT_RATE
# FROM CAR_RENTAL_COMPANY_CAR A
# JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
# ON A.CAR_ID = B.CAR_ID
# JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
# ON A.CAR_TYPE = C.CAR_TYPE
# WHERE A.CAR_TYPE = '트럭') 
# AS RESULT
# ORDER BY FEE DESC, HISTORY_ID DESC;

WITH RESULT AS (
    SELECT A.HISTORY_ID
         , A.CAR_ID
         , (DATEDIFF(END_DATE, START_DATE) + 1) AS DAILY_DURATION
         , B.CAR_TYPE
         , B.DAILY_FEE
         , CASE 
            WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 90 THEN 0.85
            WHEN (DATEDIFF(END_DATE, START_DATE) + 1) BETWEEN 30 AND 89 THEN 0.92
            WHEN (DATEDIFF(END_DATE, START_DATE) + 1) BETWEEN 7 AND 29 THEN 0.95
            ELSE 1.00
            END AS DAILY_DISCOUNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
    JOIN CAR_RENTAL_COMPANY_CAR B ON A.CAR_ID = B.CAR_ID
    WHERE B.CAR_TYPE = '트럭'
)

SELECT RESULT.HISTORY_ID, 
       ROUND(RESULT.DAILY_DURATION * RESULT.DAILY_DISCOUNT * RESULT.DAILY_FEE) AS FEE
FROM RESULT
ORDER BY FEE DESC, HISTORY_ID DESC;