-- 코드를 입력하세요
WITH REVIEW_COUNT AS (
    SELECT MEMBER_ID, COUNT(*) AS REVIEW_COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY REVIEW_COUNT DESC
    LIMIT 1
)
SELECT 
    A.MEMBER_NAME,
    B.REVIEW_TEXT,
    DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE A
JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
JOIN REVIEW_COUNT RC ON B.MEMBER_ID = RC.MEMBER_ID
ORDER BY B.REVIEW_DATE ASC, B.REVIEW_TEXT ASC;